export enum MeasurementLocation {
  ACROSS_BACK = 'across_back',
  ACROSS_FRONT = 'across_front',
  ACROSS_SHOULDER = 'across_shoulder',
  ANKLE = 'ankle',
  ARMEYE = 'arm_eye',
  ARM_LENGTH_FROM_SHOULDER = 'arm_length_from_shoulder',
  BACK_CROTCH_LENGTH = 'back_crotch_length',
  BACK_NECK_TO_EBLOW = 'back_neck_to_elbow',
  BELOW_KNEE = 'below_knee',
  BICEP = 'bicep',
  BUST = 'bust',
  BUST_POINT_TO_BUST_POINT = 'bust_point_to_bust_point',
  CALF = 'calf',
  CB_NECK_TO_WAIST = 'cb_neck_to_waist',
  CB_NECK_TO_WRIST = 'cb_neck_to_wrist',
  CF_NECK_TO_WAIST = 'cf_neck_to_waist',
  ELBOW = 'elbow',
  FOREARM = 'forearm',
  FRONT_CROTCH_LENGTH = 'front_crotch_length',
  HIGH_HIP_PLACEMENT_FROM_WAIST = 'high_hip_placement',
  HIGH_HIP = 'high_hip',
  HSP_TO_ACROSS_BACK = 'hsp_to_across_back',
  HSP_TO_ACROSS_FRONT = 'hsp_to_across_front',
  HSP_TO_BUST_POINT = 'hsp_to_bust_point',
  HSP_TO_LOW_HIP_POSITION = 'hsp_to_low_hip_position',
  HSP_TO_WAIST_POSITION = 'hsp_to_waist_position',
  INSEAM = 'inseam',
  KNEE = 'knee',
  LOW_HIP = 'low_hip',
  LOW_HIP_PLACEMENT_FROM_WAIST = 'low_hip_placement',
  MID_NECK = 'mid_neck',
  NECK_AT_BASE = 'neck_base',
  SHOULDER_DROP = 'shoulder_drop',
  SHOULDER_TO_SHOULDER = 'shoulder_to_shoulder',
  SIDE_WAIST_TO_FLOOR = 'side_waist_to_floor',
  SIDE_WAIST_TO_KNEE = 'side_waist_to_knee',
  THIGH = 'thigh',
  TOTAL_RISE_LENGTH = 'total_rise_length',
  UNDER_BUST = 'under_bust',
  VERTICAL_TRUNK = 'vertical_trunk',
  WAIST = 'waist',
  WRIST = 'wrist',
}

export const MeasurementLocationName = {
  [MeasurementLocation.ACROSS_BACK]: 'Across back',
  [MeasurementLocation.ACROSS_FRONT]: 'Across front',
  [MeasurementLocation.ACROSS_SHOULDER]: 'Across shoulder',
  [MeasurementLocation.ANKLE]: 'Ankle',
  [MeasurementLocation.ARMEYE]: 'Armeye',
  [MeasurementLocation.ARM_LENGTH_FROM_SHOULDER]: 'Arm length from shoulder',
  [MeasurementLocation.BACK_CROTCH_LENGTH]: 'Back crotch length',
  [MeasurementLocation.BACK_NECK_TO_EBLOW]: 'Back neck to eblow',
  [MeasurementLocation.BELOW_KNEE]: 'Below knee',
  [MeasurementLocation.BICEP]: 'Bicep',
  [MeasurementLocation.BUST]: 'Chest/Bust',
  [MeasurementLocation.BUST_POINT_TO_BUST_POINT]: 'Bust point to bust point',
  [MeasurementLocation.CALF]: 'Calf',
  [MeasurementLocation.CB_NECK_TO_WAIST]: 'Cb neck to waist',
  [MeasurementLocation.CB_NECK_TO_WRIST]: 'Cb neck to wrist',
  [MeasurementLocation.CF_NECK_TO_WAIST]: 'Cf neck to waist',
  [MeasurementLocation.ELBOW]: 'Elbow',
  [MeasurementLocation.FOREARM]: 'Forearm',
  [MeasurementLocation.FRONT_CROTCH_LENGTH]: 'Front crotch length',
  [MeasurementLocation.HIGH_HIP_PLACEMENT_FROM_WAIST]: 'High hip placement from waist',
  [MeasurementLocation.HIGH_HIP]: 'High hip',
  [MeasurementLocation.HSP_TO_ACROSS_BACK]: 'Hsp to across back',
  [MeasurementLocation.HSP_TO_ACROSS_FRONT]: 'Hsp to across front',
  [MeasurementLocation.HSP_TO_BUST_POINT]: 'Hsp to bust point',
  [MeasurementLocation.HSP_TO_LOW_HIP_POSITION]: 'Hsp to low hip position',
  [MeasurementLocation.HSP_TO_WAIST_POSITION]: 'Hsp to waist position',
  [MeasurementLocation.INSEAM]: 'Inseam',
  [MeasurementLocation.KNEE]: 'Knee',
  [MeasurementLocation.LOW_HIP]: 'Low hip',
  [MeasurementLocation.LOW_HIP_PLACEMENT_FROM_WAIST]: 'Low hip placement from waist',
  [MeasurementLocation.MID_NECK]: 'Mid neck',
  [MeasurementLocation.NECK_AT_BASE]: 'Neck at base',
  [MeasurementLocation.SHOULDER_DROP]: 'Shoulder drop',
  [MeasurementLocation.SHOULDER_TO_SHOULDER]: 'Shoulder to shoulder',
  [MeasurementLocation.SIDE_WAIST_TO_FLOOR]: 'Side waist to floor',
  [MeasurementLocation.SIDE_WAIST_TO_KNEE]: 'Side waist to knee',
  [MeasurementLocation.THIGH]: 'Thigh',
  [MeasurementLocation.TOTAL_RISE_LENGTH]: 'Total rise length',
  [MeasurementLocation.UNDER_BUST]: 'Under bust',
  [MeasurementLocation.VERTICAL_TRUNK]: 'Vertical trunk',
  [MeasurementLocation.WAIST]: 'Waist',
  [MeasurementLocation.WRIST]: 'Wrist',
}
