// Code generated by tygo. DO NOT EDIT.

//////////
// source: errors.go

export type Error = string;
export interface ErrorResponse {
  error: string;
}
export interface MultiErrorResponse {
  ErrorResponse: ErrorResponse;
  errors: string[];
}
export interface DependencyConflictResponse {
  ErrorResponse: ErrorResponse;
  dependencies: { [key: string]: any[]};
}
export interface ExistsResponse {
  error: string;
  id: number /* int64 */;
}
export interface ErrorOutsideRecommendedSizes {
  error: Error;
  recommended_size_id: number /* int64 */;
  available_size_ids: number /* int64 */[];
}
/**
 * Authentication errors.
 */
export const ErrPermissionDenied = any;
/**
 * Authentication errors.
 */
export const ErrTokenInvalid = any;
/**
 * Authentication errors.
 */
export const ErrTokenRevoked = any;
/**
 * Authentication errors.
 */
export const ErrTokenNotFound = any;
/**
 * Authentication errors.
 */
export const ErrUserNotAdmin = any;
/**
 * Authorization errors.
 */
export const ErrCycleWrongBrand = any;
/**
 * Authorization errors.
 */
export const ErrColorwaySizeAssetWrongBrand = any;
/**
 * Authorization errors.
 */
export const ErrStyleWrongBrand = any;
/**
 * Authorization errors.
 */
export const ErrColorwayWrongBrand = any;
/**
 * Authorization errors.
 */
export const ErrSizeWrongBrand = any;
/**
 * Authorization errors.
 */
export const ErrDivisionWrongBrand = any;
/**
 * Authorization errors.
 */
export const ErrBaseBodyWrongBrand = any;
/**
 * Authorization errors.
 */
export const ErrUserBrandMismatchBrandID = any;
/**
 * Authorization errors.
 */
export const ErrSizeSystemWrongBrand = any;
/**
 * Authorization errors.
 */
export const ErrVerticalSizeSystemWrongBrand = any;
/**
 * Authorization errors.
 */
export const ErrStyleBaseBodyAdjustmentWrongBrand = any;
/**
 * Authorization errors.
 */
export const ErrStyleCategoryBrandSpecific = any;
/**
 * Authorization errors.
 */
export const ErrUserIsNotAdmin = any;
/**
 * Authorization errors.
 */
export const ErrMeasurementLocationBrandSpecific = any;
/**
 * Database errors.
 */
export const ErrAvatarNotFound = any;
/**
 * Database errors.
 */
export const ErrBrandNotFound = any;
/**
 * Database errors.
 */
export const ErrCycleNotFound = any;
/**
 * Database errors.
 */
export const ErrColorwayNotFound = any;
/**
 * Database errors.
 */
export const ErrColorwaySizeAssetNotFound = any;
/**
 * Database errors.
 */
export const ErrStyleGarmentCategoryNotFound = any;
/**
 * Database errors.
 */
export const ErrStyleCategoryNotFound = any;
/**
 * Database errors.
 */
export const ErrGarmentCategoryNotFound = any;
/**
 * Database errors.
 */
export const ErrInvitationNotFound = any;
/**
 * Database errors.
 */
export const ErrSaleTypeNotFound = any;
/**
 * Database errors.
 */
export const ErrSizeNotFound = any;
/**
 * Database errors.
 */
export const ErrStyleNotFound = any;
/**
 * Database errors.
 */
export const ErrUserNotFound = any;
/**
 * Database errors.
 */
export const ErrUserRoleNotFound = any;
/**
 * Database errors.
 */
export const ErrSizeValueNotFound = any;
/**
 * Database errors.
 */
export const ErrStartSizeValueNotFound = any;
/**
 * Database errors.
 */
export const ErrStartVerticalSizeValueNotFound = any;
/**
 * Database errors.
 */
export const ErrVerticalSizeValueNotFound = any;
/**
 * Database errors.
 */
export const ErrDivisionNotFound = any;
/**
 * Database errors.
 */
export const ErrBaseBodyNotFound = any;
/**
 * Database errors.
 */
export const ErrMeasurementUnitNotFound = any;
/**
 * Database errors.
 */
export const ErrReferenceSizeValueIDNotFound = any;
/**
 * Database errors.
 */
export const ErrMeasurementLocationNotFound = any;
/**
 * Database errors.
 */
export const ErrCategorySubcategoryMeasurementLocationsNotFound = any;
/**
 * Database errors.
 */
export const ErrCategoryMeasurementLocationsNotFound = any;
/**
 * Database errors.
 */
export const ErrCycleSeasonNotFound = any;
/**
 * Database errors.
 */
export const ErrBaseBodyMeasurementNotFound = any;
/**
 * Database errors.
 */
export const ErrGarmentMeasurementNotFoundInBaseBodyMeasurements = any;
/**
 * Database errors.
 */
export const ErrFitNotFound = any;
/**
 * Database errors.
 */
export const ErrRoleNotFound = any;
/**
 * Database errors.
 */
export const ErrSizeSystemNotFound = any;
/**
 * Database errors.
 */
export const ErrVerticalSizeSystemNotFound = any;
/**
 * Database errors.
 */
export const ErrSizingChartNotFound = any;
/**
 * Database errors.
 */
export const ErrMeasurementLocationGroupNotFound = any;
/**
 * Database errors.
 */
export const ErrShopifyStoreNotFound = any;
export const ErrBrandStyleIDExists = any;
export const ErrColorwaySKUExists = any;
export const ErrEmailExists = any;
export const ErrInvitationExists = any;
export const ErrUserExists = any;
export const ErrFirebaseUserExists = any;
export const ErrUserIDExists = any;
export const ErrCycleSeasonYearExists = any;
export const ErrCycleQuarterDropYearExists = any;
export const ErrSizeSystemNameExists = any;
export const ErrStyleCategoryNameExists = any;
export const ErrGarmentCategoryNameExists = any;
export const ErrStyleGarmentCategoryExists = any;
export const ErrMeasurementLocationExists = any;
export const ErrShopifyStoreNameExists = any;
export const ErrInvalidStoreName = any;
/**
 * Parsing and type errors.
 */
export const ErrHeightExpectsFloatString = any;
/**
 * Parsing and type errors.
 */
export const ErrSkinToneFactorExpectsFloatString = any;
/**
 * Parsing and type errors.
 */
export const ErrWeightExpectsFloatString = any;
/**
 * Parsing and type errors.
 */
export const ErrFrameCountExpectsIntString = any;
/**
 * Parsing and type errors.
 */
export const ErrBrandIDExpectsIntString = any;
/**
 * Parsing and type errors.
 */
export const ErrEmptyResourceID = any;
/**
 * Parsing and type errors.
 */
export const ErrIDParse = any;
/**
 * Parsing and type errors.
 */
export const ErrCycleIDParse = any;
/**
 * Parsing and type errors.
 */
export const ErrDivisionIDParse = any;
/**
 * Parsing and type errors.
 */
export const ErrStyleIDParse = any;
/**
 * Parsing and type errors.
 */
export const ErrColorwaySizeAssetIDParse = any;
/**
 * Parsing and type errors.
 */
export const ErrSizeIDParse = any;
/**
 * Parsing and type errors.
 */
export const ErrColorwayIDParse = any;
/**
 * Parsing and type errors.
 */
export const ErrDateOfBirthFormatWrong = any;
/**
 * Parsing and type errors.
 */
export const ErrBodyTypeNotNumber = any;
/**
 * Validation errors.
 */
export const ErrDateStartRequired = any;
/**
 * Validation errors.
 */
export const ErrDateEndRequired = any;
/**
 * Validation errors.
 */
export const ErrDateEndBeforeDateStart = any;
/**
 * Validation errors.
 */
export const ErrColorwayRequired = any;
/**
 * Validation errors.
 */
export const ErrGenderOrBodyTypeRequired = any;
/**
 * Validation errors.
 */
export const ErrSkuRequired = any;
/**
 * Validation errors.
 */
export const ErrSizeRequired = any;
/**
 * Validation errors.
 */
export const ErrCycleSeasonOrQuarterRequired = any;
/**
 * Validation errors.
 */
export const ErrBaseBodyRequired = any;
/**
 * Validation errors.
 */
export const ErrReferenceSizeRequired = any;
/**
 * Validation errors.
 */
export const ErrUserBrandRequired = any;
/**
 * Validation errors.
 */
export const ErrMeasurementLocationRequired = any;
/**
 * Validation errors.
 */
export const ErrBaseBodyMeasurementRequired = any;
/**
 * Validation errors.
 */
export const ErrBaseBodyMeasurementsEmpty = any;
/**
 * Validation errors.
 */
export const ErrReferenceSizeValueIDRequired = any;
/**
 * Validation errors.
 */
export const ErrStyleRequiresSize = any;
/**
 * Validation errors.
 */
export const ErrReferenceSizeValueIDNotInSizeSystem = any;
/**
 * Validation errors.
 */
export const ErrReferenceSizeValueIDNotInSizesSizeValues = any;
/**
 * Validation errors.
 */
export const ErrVerticalSizeValueNotInVerticalSizeSystem = any;
/**
 * Validation errors.
 */
export const ErrVerticalReferenceSizevalueNotInVerticalSizes = any;
/**
 * Validation errors.
 */
export const ErrMeasurementLocationBrandMismatch = any;
/**
 * Validation errors.
 */
export const ErrVerticalSizeValueIDRequired = any;
/**
 * Validation errors.
 */
export const ErrGarmentMeasurementRequired = any;
/**
 * Validation errors.
 */
export const ErrCategoryMeasurementLocationsRequired = any;
/**
 * Validation errors.
 */
export const ErrGarmentCategoryRequired = any;
/**
 * Validation errors.
 */
export const ErrSizeSystemHorizontalOrVerticalRequired = any;
/**
 * Validation errors.
 */
export const ErrSizeSystemRequiresSizeValue = any;
/**
 * Validation errors.
 */
export const ErrMeasurementLocationsFemaleRequired = any;
/**
 * Validation errors.
 */
export const ErrMeasurementLocationsMaleRequired = any;
/**
 * Validation errors.
 */
export const ErrMeasurementLocationReferencesSelf = any;
/**
 * Validation errors.
 */
export const ErrFirebasePasswordTooShort = any;
/**
 * Validation errors.
 */
export const ErrAPIKeyRequired = any;
/**
 * Validation errors.
 */
export const ErrNoFramesFound = any;
/**
 * Validation errors.
 */
export const ErrMultipleValidationErrors = any;
/**
 * Validation errors.
 */
export const ErrGLBNotFound = any;
/**
 * Validation errors.
 */
export const ErrSDFNotFound = any;
/**
 * Validation errors.
 */
export const ErrVTODisabled = any;
/**
 * State errors
 */
export const ErrStyleNotPublished = any;
/**
 * State errors
 */
export const ErrVTOInProgress = any;
/**
 * State errors
 */
export const ErrInvitationExpired = any;
/**
 * State errors
 */
export const ErrAvatarNotCreated = any;
/**
 * State errors
 */
export const ErrAvatarAlreadyCreated = any;
/**
 * State errors
 */
export const ErrAvatarNotReady = any;
/**
 * State errors
 */
export const ErrShopifyStoreDisabled = any;
/**
 * State errors
 */
export const ErrNoDaysInPastBeforeReturnWindow = any;
export const ErrResourceDependencyConflict = any;
export const ErrCycleQuarterOutsideRange = any;
export const ErrCycleQuarterDropOutsideRange = any;
export const ErrValueStretchTooLarge = any;
export const ErrBaseBodyMeasurementValueTooLarge = any;
export const ErrSkinToneFacExpectsBetween0And1 = any;
export const ErrMaterialMultipleNotAllowed = any;
export const ErrObjectMultipleNotAllowed = any;
export const ErrSizeIDOutsideRecommendedRange = any;
export const ErrCycleDateInvalidRange = any;
export const ErrBaseBodyMeasurementMustGtZero = any;
export const ErrStyleBaseBodyAdjustmentValueTooLarge = any;
export const ErrSizeSystemNotVertical = any;
export const ErrSizeSystemNotHorizontal = any;
export const ErrColorwayNotInAllSizes = any;
export const ErrSizeLabelDuplicated = any;
export const ErrSizeDuplicated = any;
export const ErrCycleStyleDuplicated = any;
export const ErrBaseBodyLabelDuplicated = any;
export const ErrMeasurementLocationDuplicated = any;
export const ErrSizingChartNameDuplicated = any;
export const ErrSizeValueDuplicated = any;
export const ErrColorwayNameDuplicated = any;
export const ErrColorwaySizeAssetSKUDuplicated = any;
/**
 * File upload errors.
 */
export const ErrZipInvalid = any;
/**
 * File upload errors.
 */
export const ErrZipObjNotFound = any;
/**
 * File upload errors.
 */
export const ErrZipMtlNotFound = any;
/**
 * File upload errors.
 */
export const ErrZipContentsNotAllowed = any;
/**
 * File upload errors.
 */
export const ErrFileSizeTooLarge = any;
/**
 * File upload errors.
 */
export const ErrZipCompressionUnsupported = any;
/**
 * File upload errors.
 */
export const ErrContentTypeNotAllowed = any;
/**
 * File upload errors.
 */
export const ErrFileSizeEmpty = any;
/**
 * File upload errors.
 */
export const ErrGLBSuffixNotFound = any;
/**
 * File upload errors.
 */
export const ErrGlBSizeEmpty = any;
