name: Deploy To Dev

on:
  pull_request_target:
    types:
      - closed

permissions:
  id-token: write
  contents: write

jobs:
  get_version_label:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    uses: ./.github/workflows/get-version-label.yaml
  build:
    if: github.event.pull_request.merged == true && needs.get_version_label.outputs.version_label != 'chore'
    runs-on: ubuntu-latest
    needs: get_version_label
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Fetch all branches/tags
        run: |
          git fetch --all

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Bump Version
        env:
          GITHUB_TOKEN: ${{ secrets.SDK_PUSH_PAT}}
        run: |
          npm version "${{ needs.get_version_label.outputs.version_label }}"
          NEW_VERSION=$(npm pkg get version | tr -d '"')
          git add package.json package-lock.json

      - name: Build
        run: |
          mv .env .env.tmp
          envsubst < .env.tmp > .env
          npm run build:dev

      - name: Publish to NPM (next)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --access public --tag next --verbose

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::602373492013:role/github_actions
          aws-region: us-west-2

      - name: Upload assets to S3
        run: |
          aws s3 cp ./dist/esm/index.js s3://tfr-assets-dev/shop-sdk/${{ github.ref_name }}/index.js

      - name: Commit and Push Version
        run: |
          git commit -m "${{ needs.get_version_label.outputs.version_label }}(next): ${NEW_VERSION}"
          git push origin main --follow-tags
