name: Deploy to dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          echo $GITHUB_SHA
          envsubst < .env.dev > .env.dev
          NODE_ENV=dev npm run build:rollup

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::602373492013:role/github_actions
          aws-region: us-west-2

      - name: Upload js to S3
        run: |
          aws s3 cp ./dist/esm/main.js s3://tfr-assets-dev/shop-sdk/${GITHUB_SHA::7}/main.js

      - name: Upload css to S3
        run: aws s3 cp --recursive src/styles/ s3://tfr-assets-dev/shop-sdk/${GITHUB_SHA::7}/styles/

      - name: Upload languages to S3
        run: aws s3 cp --recursive src/languages/ s3://tfr-assets-dev/shop-sdk/${GITHUB_SHA::7}/languages/
