name: Deploy to dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Derive version label from merge commit labels
        run: |
          echo "LABEL=$(node scripts/get-version-label.js)" >> $GITHUB_ENV

      - name: Bump version after merge
        if: ${{ env.LABEL != '' }}
        run: |
          npm version "$LABEL"
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -am "ci: bump version ($LABEL)"
          git tag v$(node -p "require('./package.json').version")
          git push --follow-tags

      - name: Build
        run: |
          mv .env .env.tmp
          envsubst < .env.tmp > .env
          NODE_ENV=dev npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::602373492013:role/github_actions
          aws-region: us-west-2

      - name: Upload assets to S3
        run: |
          aws s3 cp ./dist/esm/index.js s3://tfr-assets-dev/shop-sdk/${{ github.ref_name }}/index.js

      - name: Publish to npm (next)
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          npm publish --access public --tag next --verbose
