name: Get Version Label
on:
  pull_request:
    branches:
      - main
    types: [labeled, unlabeled]
  workflow_call:
    outputs:
      version_label:
        description: the major, minor or patch version label
        value: ${{ jobs.get_label.outputs.version_label }}

permissions:
  contents: read

jobs:
  get_label:
    runs-on: ubuntu-latest
    outputs:
      version_label: ${{ steps.get_label.outputs.version_label }}
    steps:
      - name: Require patch/minor/major label
        id: get_label
        uses: actions/github-script@v7
        with:
          script: |
            const allowed = ['patch', 'minor', 'major'];
            const versionLabels = context.payload.pull_request.labels.map(l => l.name.toLowerCase()).filter(label => allowed.includes(label));

            if (versionLabels.length === 0) {
              core.setFailed(`PR must contain one of the version labels: ${allowed.join(', ')}`);
            } else if (versionLabels.length > 1) {
              core.setFailed(`PR contains multiple version labels: ${versionLabels.join(', ')}. Only one of ${allowed.join(', ')} is allowed.`);
            }
            core.setOutput('version_label', versionLabels[0]);
            core.info("version_label", versionLabels[0]);
