name: Get Version Label
on:
  pull_request:
    branches:
      - main
    types: [opened, edited, labeled, unlabeled, synchronize]

permissions:
  contents: read

jobs:
  get_version_label:
    runs-on: ubuntu-latest
    outputs:
      version_label: ${{ steps.get_version_label.outputs.version_label }}
    steps:
      - name: Require patch/minor/major label
        id: get_version_label
        uses: actions/github-script@v7
        with:
          script: |
            const allowed = ['patch', 'minor', 'major'];
            const versionLabels = context.payload.pull_request.labels.map(l => l.name.toLowerCase()).filter(label => allowed.includes(label));

            if (versionLabels.length === 0) {
              core.setFailed(`PR must contain one of the version labels: ${allowed.join(', ')}`);
            } else if (versionLabels.length > 1) {
              core.setFailed(`PR contains multiple version labels: ${versionLabels.join(', ')}. Only one of ${allowed.join(', ')} is allowed.`);
            }
            core.setOutput('version_label', versionLabels[0]);
            core.info(`version_label: ${versionLabels[0]}`);

      - name: Check Version
        id: check_feature_tags
        run: |
          VERSION_LABEL="${{ steps.get_version_label.outputs.version_label }}"

          # Check if the version label tag exists on any commit reachable from HEAD
          # but not from origin/main. This effectively checks if the tag was introduced
          # within the feature branch's commits.
          if git describe --tags --exact-match --contains "$VERSION_LABEL" $(git rev-list origin/main..HEAD) &>/dev/null; then
            echo "version_bump_exists=true" >> $GITHUB_OUTPUT
            echo "Version bump tag '$VERSION_LABEL' already exists on feature branch"
          else
            echo "version_bump_exists=false" >> $GITHUB_OUTPUT
            echo "No '$VERSION_LABEL' tag found on feature branch"
          fi

      - name: Bump Version
        if: ${{ steps.check_feature_tags.outputs.version_bump_exists == 'false' }}
        run: |
          # Configure Git user for the commit
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          VERSION_LABEL="${{ steps.get_version_label.outputs.version_label }}"
          npm version "$VERSION_LABEL" -m "ci: bump version to %s"
          git push origin HEAD:"${GITHUB_REF}" --follow-tags
