name: PR Label Guard

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, labeled]

permissions:
  contents: read

jobs:
  ensure-label:
    runs-on: ubuntu-latest
    steps:
      - name: Require patch/minor/major label
        uses: actions/github-script@v7
        with:
          script: |
            const allowed = ['patch','minor','major'];
            const labels = context.payload.pull_request.labels.map(l => l.name);
            if(!labels.some(l => allowed.includes(l))){
              core.setFailed(`PR must contain one of the version labels: ${allowed.join(', ')}`);
            }
