name: Production Release

on:
  release:
    types: [released]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          mv .env .env.tmp
          envsubst < .env.tmp > .env
          NODE_ENV=prod npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::496310237386:role/github_actions
          aws-region: us-west-2

      - name: Upload assets to S3
        run: |
          aws s3 cp ./dist/esm/index.min.js s3://tfr-assets-prod/shop-sdk/${{ github.ref_name }}/index.min.js
          aws s3 cp ./dist/esm/index.js s3://tfr-assets-prod/shop-sdk/${{ github.ref_name }}/index.js

      - name: Publish to npm (latest)
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          npm publish --access public --tag latest
